---
# tasks for restart tomcat
- name: ==> shutdown qle tomcat ,path = "{{ root_location }}tomcat/{{ tomcat_version }}/bin/"
  command: sh {{ root_location }}tomcat/{{ tomcat_version }}/bin/shutdown.sh
  become: true
  become_user: rezuser

- name: ==> sleep 5s
  command: sleep 5s
  
- name: Check if Apache is running
  shell: ps aux | grep '[/]{{ root_location }}tomcat/{{ tomcat_version }}/' | awk '{print $2}'
  ignore_errors: yes
  changed_when: false
  register: service_apache_status
  
- debug: msg="Check if Apache is running {{ service_apache_status }}"
- debug: msg="service_apache_status.stdout != '' =  {{ service_apache_status.stdout != ''}}"

- name: kill process is tomcat is still running
  shell: kill $(ps aux | grep '[/]{{ root_location }}tomcat/{{ tomcat_version }}/' | awk '{print $2}')
  when: service_apache_status.stdout != ''

- command: sleep 1s
  when: service_apache_status.stdout != ''
    
- name: ==> startup qle tomcat , path = {{ root_location }}tomcat/{{ tomcat_version }}/bin/startup.sh
  shell: setsid /bin/sh -i -c "{{ root_location }}tomcat/{{ tomcat_version }}/bin/startup.sh"
  become: true
  become_user: rezuser
