---
# tasks file for nginx

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: true

- name: Install nginx
  apt: name={{ item }} state=present
  become: true
  with_items:
    - nginx

- name: Add nginx.conf
  template:
    src: nginx.conf
    dest: "/etc/nginx/nginx.conf"  

- name: Start nginx
  become: true
  service:
    name: nginx
    state: started
    
#- name: Add nginx.conf
  #template: "src=nginx.conf dest=/etc/nginx"
  #become: yes
 
- name: restart nginx
  service: name=nginx state=restarted