---
- hosts: webservers
  become: yes
  become_method: sudo
  remote_user: ubuntu
  vars:
    root_location: "/system/"
    user_name: "ubuntu"
    os_name: "ubuntu"     
    soft_from_remote: true
    
    tomcat_version: "apache-tomcat-8.0.36"
    java_version: "jdk1.8.0_144"
    jdk_archive_file: "jdk1.8.0_144.tar.gz"
    
    nexus_server: "nexus.rezos.io"
    nexus_user_name: "thusitha"
    nexus_password: "123456"
    
    mysql_root_password: "12345678"
       
    github_token: "3d26fa975ad28908cf909ab4f7551a979f26c1b6" 
    github_user: "idthusitha"
    github_repocitory: "spring-boot-web-application"
    deploy_war_name: "spring-boot-web-application.war"
    
    gradle_version: "5.2.1"
    gradle_zipfile: "gradle-{{gradle_version}}-all.zip"
    gradle_folder: "gradle-{{gradle_version}}"
  roles:
    -  default
    -  nginx
    -  java
    -  mysql
    -  tomcat
    -  tomcat-restart
    -  release
    -  build
    -  deploy
    -  tomcat-restart
